### ISSUE TITLE
Use the Leaflet Cluster plugin

### ISSUE THREAD

**Issue by herlon214** [brandonxiang/vueleaflet#10]
Can I use the Leaflet Cluster plugin with this components?

**Comment by brandonxiang** [comment]
use `addControl` in vuex

**Comment by brandonxiang** [comment]
I refactor the code for vue3.

We can support the third-party plugin now, like follows example.

https://github.com/brandonxiang/vueleaflet/blob/next/examples/LCustomPlugin.vue
