### ISSUE TITLE
Map object reference

### ISSUE THREAD

**Issue by perezale** [brandonxiang/vueleaflet#11]
Hi, I'm wondering how could I access the map object to add some additional stuff. Couldn't see any of it in the docs.
I'd like to use vueleaflet as a base map (it worked straightforward ❤️ ) and extend it as I used to do before vue, using the object obtained from

map = new L.Map('map', ...

For example, I need to add another control to the map (Leaflet Draw) using this line. 

map.addControl(drawControl);

any ideas? thanks

**Comment by brandonxiang** [comment]
Review this

https://github.com/brandonxiang/vue-leaflet-mobile/blob/develop/src/views/Map.vue#L42
