### ISSUE TITLE
Cannot set property 'render' of undefined(…) when adding tilelayer

### ISSUE THREAD

**Issue by Shinjirius** [brandonxiang/vueleaflet#4]
I am trying to use this vue-leaflet component but I am getting the following error:
> Uncaught TypeError: Cannot set property 'render' of undefined(…)

This happens whenever I add a tile layer to the component.

This is my component:
[MyMap.vue](https://github.com/brandonxiang/vue-leaflet/files/633463/MyMap.txt)

Is this a bug or am I doing something wrong?

**Comment by brandonxiang** [comment]
Would you mind to open a repo in your error situation?

**Comment by thulioph** [comment]
Hey @Shinjirius, how do you solve this problem? I have the same problem here.

**Comment by Dark-Energy** [comment]
@thulioph react or self-written framework (it's not so difficult, though take many time).
