### ISSUE TITLE
Example code not working

### ISSUE THREAD

**Issue by rbrtmrtn** [brandonxiang/vueleaflet#6]
Hello! I'm having some trouble getting the code from the readme to work. When you do this:

    import map from "./components/Map.vue"

it imports an object of options, but not a Vue component. So when you use it in the example template:

```
<template>
  <map :zoom="zoom" :center="center">
      <tilelayer :url="url"></tilelayer>
      <marker :position="center"></marker>
    </map>
</template>
```

you get a Vue error. Should `VueLeaflet.Map` point to `mapComponent` instead?

**Comment by brandonxiang** [comment]
The current version only supports vue 1.0. The vue2.0 will be supported in another branch vue2leaflet1
