### ISSUE TITLE
Error Message "Map is already initialized"

### ISSUE THREAD

**Issue by Templum** [brandonxiang/vueleaflet#7]
Hello,

My project has two pages which include vueleaflet. I also use vue-router with those pages(/components). During the first visit (doesn't matter on which component) the map gets displayed as planned. When I then visit the page which contains the other map, I receive the following message: "Map container is already initialized.". 

If you like you can try it out yourself visit templum.me, you should see the map displayed. Then head over to "Veransltatungsort" under "Hier finden sie uns" the other map should be displayed. Within console, the exception should get displayed. 

As far as I saw in your code a solution would be freeing/destroying the map object on unmount. Or give the option to set the used id with a property. 

Best Regards
Simon

**Comment by brandonxiang** [comment]
this project uses vuex to store map object. Since
 right now, only one map is support. Maybe
you should try vue2leaflet

**Comment by Templum** [comment]
Just to point that out, I don't display two maps at the same time. But it seems like I described that you should ensure before recreating the map if there is already something in the store. This error only occurs when I navigate straight from one page containing a map to the other page containing a map. (With vue-router) When I instead navigate to another page before navigating to the page containing a map, all is fine.

**Comment by brandonxiang** [comment]
I have updated the package to 2.0.12, which is support 2 maps. Check it out, update package please.

**Comment by brandonxiang** [comment]
@Templum name div with different names

**Comment by Templum** [comment]
@brandonxiang Thank you for solving that Issue. Really appreciate it.
