### ISSUE TITLE
Comparison with vue2-leaflet

### ISSUE THREAD

**Issue by gagan-bansal** [brandonxiang/vueleaflet#8]
Hi, Nice project. 

I see this and [vue2-leaflet](https://github.com/KoRiGaN/Vue2Leaflet) as vueified leaflet project. 
Could you please throw some light on how this project `vueleaflet` differes with `vue2-leaflet` as architectural point of view.

Thanks

**Comment by brandonxiang** [comment]
One year ago, there is no vueified leaflet project. I was inspired by react-leaflet. I created a vue-leaflet by vue1.0 and leaflet0.7. At that time, with limited knowledge, I had not carried the project quiet well.

Then, a year later, vue2leaflet came out with vue 2.0. It is wonderful project, also, giving me much inspirations.

Vue2leaflet is a transditional vue project with `emit` and `on`. However, vue-leaflet is a modern type of vue project with vuex. It is convenient for map management, and data async processing.

**Comment by gagan-bansal** [comment]
Thanks @brandonxiang for update. 
Yes as you say vuex seems suitable choice for projects with maps data. 

I am closing this and creating new ticket for usage.
